from data_loader import fetch_stock_data
from preprocessing import preprocessing_data,compute_log_returns
import numpy as np 
import pandas as pd
from hmm_model import train_hmm,hmm_parameters


if __name__=="__main__":
    stock_data=fetch_stock_data()
    preprocessed_data=preprocessing_data(stock_data)
    hmm_model,hmm_hidden_states=train_hmm(stock_data)


    print(f"Sequence of possible hidden state generated by HMM model is:{hmm_hidden_states[:10]}")

    print(len(hmm_hidden_states))
    print(len(preprocessed_data))
    hmm_parameters(hmm_model)

    